### ISSUE TITLE
Setup the Repo

### ISSUE THREAD

**Issue by rhettg** [rhettg/cuddly-sniffle#1]
Let's setup this repository.

We're creating a flask app to build a platform for tagging and reviewing data. The data will come in the form of a yaml file that lists a set of documents for review, the questions, and the potential tags.

The web app will facilitate reviewing each document / question pair and allow the user to select the tag.

Let's say our document looks something like:

```yaml
---
questions:
  - what is the capital of France
  - what are the names of all the oceans on earth
  - how many people live on Mars
tags:
  - relevant
  - highly-relevant
  - not-relevant
documents:
  - id: <document id>
    content: <document content>  
```

The output will be another yaml file with the answers from the user.

The content will be markdown formatted.

The technology stack should consist of Flask, Ninja Tailwind and a component library like sailboat ui.
