### ISSUE TITLE
Implement document viewing

### ISSUE THREAD

**Issue by rhettg** [rhettg/cuddly-sniffle#3]
We're creating a flask app to build a platform for tagging and reviewing data. The data will come in the form of a yaml file that lists a set of documents for review, the questions, and the potential tags.

The web app will facilitate reviewing each document / question pair and allow the user to select the tag.

Let's say our document looks something like:

```yaml
---
questions:
  - what is the capital of France
  - what are the names of all the oceans on earth
  - how many people live on Mars
tags:
  - relevant
  - highly-relevant
  - not-relevant
documents:
  - id: <document id>
    content: <document content>  
```

The Ui will then allow reviewing each document and question combination one by one. The user will be able to click a button on appropriate tag which posts back the app, records the results, then moves on to the next item to review. Let's just store the results in another yaml file.
